version: '3.8'

services:
  tomcat:
    image: my-custom-tomcat:latest  # Specify the image name
    build: .              # Build the image from the Dockerfile in the current directory
    container_name: my-tomcat-container  # Custom container name
    ports:
      - "8090:8080"  # Maps port 8090 on host to port 8090 in the container